In [1]:
import numpy as np
import pandas as pd
!pip install chardet

Requirement already satisfied: chardet in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (5.2.0)

In [3]:
df = pd.read_csv("fortune500.csv")

In [4]:
df.head(2)

,lon,lat,company,location,industry,state,city
0,-94.2088,36.3729,Walmart,"Bentonville, AR",General Merchandisers,AR,Bentonville
1,-96.9489,32.8140,Exxon Mobil,"Irving, TX",Petroleum Refining,TX,Irving

In [10]:
industries=df.groupby('industry')

In [11]:
industries

In [12]:
len(df)

1000

In [13]:
len(industries)

74

In [17]:
industries.size().sort_values(ascending=False)

industry
Specialty Retailers: Other                  43
Utilities: Gas and Electric                 39
Mining, Crude-Oil Production                35
Chemicals                                   34
Insurance: Property and Casualty (Stock)    28
                                            ..
Railroads                                    4
Education                                    3
Advertising, marketing                       2
Mail, Package, and Freight Delivery          2
Toys, Sporting Goods                         2
Length: 74, dtype: int64

In [18]:
industries.first()

,lon,lat,company,location,state,city
industry,,,,,,
"Advertising, marketing",-74.0059,40.7128,Omnicom Group,"New York, NY",NY,New York
Aerospace and Defense,-87.6298,41.8781,Boeing,"Chicago, IL",IL,Chicago
Airlines,-97.3308,32.7555,American Airlines Group,"Fort Worth, TX",TX,Fort Worth
Apparel,-122.8040,45.4871,Nike,"Beaverton, OR",OR,Beaverton
"Automotive Retailing, Services",-80.1373,26.1224,AutoNation,"Fort Lauderdale, FL",FL,Fort Lauderdale
...,...,...,...,...,...,...
Wholesalers: Diversified,-80.1918,25.7617,World Fuel Services,"Miami, FL",FL,Miami
Wholesalers: Electronics and Office Equipment,-117.8680,33.7456,Ingram Micro,"Santa Ana, CA",CA,Santa Ana
Wholesalers: Food and Grocery,-95.3698,29.7604,Sysco,"Houston, TX",TX,Houston
Wholesalers: Health Care,-122.4190,37.7749,McKesson,"San Francisco, CA",CA,San Francisco
zMiscellaneous,-93.0900,44.9537,3M,"St. Paul, MN",MN,St. Paul

In [19]:
industries.last()

,lon,lat,company,location,state,city
industry,,,,,,
"Advertising, marketing",-74.0059,40.7128,Interpublic Group,"New York, NY",NY,New York
Aerospace and Defense,-87.9790,41.9634,AAR,"Wood Dale, IL",IL,Wood Dale
Airlines,-157.8580,21.3069,Hawaiian Holdings,"Honolulu, HI",HI,Honolulu
Apparel,-122.6760,45.5231,Columbia Sportswear,"Portland, OR",OR,Portland
"Automotive Retailing, Services",-98.1245,29.7030,Rush Enterprises,"New Braunfels, TX",TX,New Braunfels
...,...,...,...,...,...,...
Wholesalers: Diversified,-90.1009,30.4755,Pool,"Covington, LA",LA,Covington
Wholesalers: Electronics and Office Equipment,-82.3940,34.8526,ScanSource,"Greenville, SC",SC,Greenville
Wholesalers: Food and Grocery,-118.1600,34.0006,Unified Grocers,"Commerce, CA",CA,Commerce
Wholesalers: Health Care,-93.0900,44.9537,Patterson,"St. Paul, MN",MN,St. Paul
zMiscellaneous,-118.2550,34.1425,Public Storage,"Glendale, CA",CA,Glendale

In [44]:
industries['lat'].mean()

industry
Advertising, marketing                           40.712800
Aerospace and Defense                            40.008214
Airlines                                         35.988775
Apparel                                          38.723560
Automotive Retailing, Services                   35.347989
                                                   ...
Wholesalers: Diversified                         37.895938
Wholesalers: Electronics and Office Equipment    35.342263
Wholesalers: Food and Grocery                    38.031650
Wholesalers: Health Care                         40.217617
zMiscellaneous                                   36.005550
Name: lat, Length: 74, dtype: float64

In [20]:
industries.groups

{'Advertising, marketing': [199, 371], 'Aerospace and Defense': [26, 44, 63, 99, 123, 128, 218, 251, 301, 389, 395, 506, 538, 602, 603, 643, 824, 833, 903, 933, 971, 996], 'Airlines': [69, 72, 78, 160, 453, 483, 710, 919], 'Apparel': [105, 247, 350, 373, 489, 534, 540, 678, 738, 778, 805, 890, 899, 976, 981], 'Automotive Retailing, Services': [155, 176, 231, 290, 314, 335, 449, 481, 545], 'Beverages': [62, 367, 436, 529, 548, 605, 755, 874], 'Building Materials, Glass': [497, 652, 714, 754, 763, 816], 'Chemicals': [47, 86, 196, 197, 212, 248, 258, 265, 283, 304, 319, 370, 394, 426, 502, 542, 563, 569, 581, 588, 612, 637, 660, 707, 736, 781, 799, 836, 870, 882, 915, 937, 953, 978], 'Commercial Banks': [20, 22, 27, 29, 75, 81, 87, 125, 137, 188, 191, 277, 291, 294, 302, 326, 415, 478, 544, 570, 591, 661, 764, 827, 906, 969], 'Computer Peripherals': [120, 204, 427, 655], 'Computer Software': [30, 80, 404, 482, 567, 571, 584, 604, 670, 808, 861, 912, 994], 'Computers, Office Equipment': [4, 18, 411, 635, 742], 'Construction and Farm Machinery': [53, 85, 153, 295, 376, 628, 641, 728, 962], 'Diversified Financials': [7, 16, 41, 92, 234, 246, 372, 462, 557, 698, 750, 790, 950, 967], 'Diversified Outsourcing Services': [206, 250, 514, 565, 653, 675, 688, 729, 782, 793, 859, 877, 907, 952], 'Education': [669, 745, 929], 'Electronics, Electrical Equip.': [73, 119, 147, 408, 442, 485, 694, 704, 871, 898, 910, 921], 'Energy': [195, 348, 352, 369, 445, 555, 608, 624, 648, 691, 711, 747, 800, 864, 873, 893], 'Engineering, Construction': [135, 238, 285, 342, 360, 420, 423, 479, 561, 572, 869, 928, 983], 'Entertainment': [56, 96, 103, 211, 221, 391, 428, 429, 577, 748, 756, 773, 775, 819, 826, 948], 'Financial Data Services': [237, 264, 307, 421, 467, 493, 499, 511, 723, 806, 841, 848, 850, 876, 885, 920, 941], 'Food Consumer Products': [43, 90, 164, 170, 172, 202, 209, 271, 305, 309, 341, 375, 466, 583, 597, 613, 646, 677, 685, 766, 838, 891, 966], 'Food Production': [33, 68, 82, 243, 416, 461, 568, 621, 735, 802], 'Food Services': [109, 186, 227, 324, 579, 610, 776, 817, 856, 992], 'Food and Drug Stores': [9, 19, 34, 83, 100, 116, 163, 213, 606, 636, 676, 761, 801, 830, 863, 945], 'Forest and Paper Products': [354, 469, 595, 820], 'General Merchandisers': [0, 35, 98, 104, 156, 158, 223, 249, 280, 399, 609, 787], 'Health Care: Insurance and Managed Care': [13, 37, 48, 57, 89, 185, 215, 233, 300, 644, 918, 995], 'Health Care: Medical Facilities': [74, 134, 169, 230, 323, 490, 494, 638, 741, 770, 892], 'Health Care: Pharmacy and Other Services': [21, 374, 413, 439, 475, 586, 689, 788, 815, 825, 884, 932], 'Home Equipment, Furnishings': [260, 333, 347, 454, 587, 622, 757, 758, 943], 'Homebuilders': [353, 363, 452, 576, 627, 734, 829, 886, 894, 956, 990], 'Hotels, Casinos, Resorts': [208, 220, 279, 288, 327, 441, 476, 496, 582, 814, 839, 934], 'Household and Personal Products': [31, 139, 178, 270, 321, 446, 468, 566, 578, 701, 834, 844], 'Industrial Machinery': [200, 229, 345, 527, 541, 558, 625, 631, 681, 692, 746, 769, 771, 785, 791, 792, 795, 804, 822, 851, 872, 905, 968, 985, 993], 'Information Technology Services': [23, 142, 228, 252, 287, 474, 505, 629, 673, 695, 998], 'Insurance: Life, Health (Mutual)': [79, 91, 93, 108, 253, 332, 480, 878, 889, 938], 'Insurance: Life, Health (stock)': [38, 54, 131, 222, 267, 272, 278, 281, 303, 386, 390, 585, 601, 607, 620, 686, 743, 803, 954, 963, 979], 'Insurance: Property and Casualty (Mutual)': [40, 84, 263, 424, 680, 798, 982], 'Insurance: Property and Casualty (Stock)': [3, 45, 77, 88, 111, 121, 152, 159, 210, 214, 284, 313, 357, 384, 435, 458, 471, 498, 503, 510, 524, 553, 575, 614, 751, 823, 949, 997], 'Internet Services and Retailing': [28, 39, 171, 241, 262, 338, 457, 560, 717, 732, 762, 857, 944], 'Mail, Package, and Freight Delivery': [46, 64], 'Medical Products and Equipment': [133, 184, 299, 337, 377, 465, 554, 634, 699, 712, 744, 765, 772, 855, 917, 958, 972], 'Metals': [124, 138, 175, 282, 325, 387, 414, 546, 600, 665, 727, 852, 961, 989], 'Mining, Crude-Oil Production': [50, 114, 136, 141, 151, 161, 166, 217, 226, 349, 378, 397, 495, 504, 519, 535, 559, 593, 617, 633, 651, 666, 720, 737, 767, 810, 812, 821, 858, 887, 888, 902, 925, 960, 984], 'Motor Vehicles and Parts': [5, 8, 65, 157, 165, 173, 174, 275, 311, 340, 343, 346, 393, 409, 640, 656, 667, 687, 706, 716, 783, 784, 811, 955, 973], 'Network and Other Communications Equipment': [59, 112, 296, 362, 486, 491, 516, 556, 580, 639, 683, 724, 927, 946], 'Oil and Gas Equipment, Services': [95, 118, 126, 274, 356, 447, 522, 549, 654, 659, 719, 777, 914, 942, 986, 991], 'Packaging, Containers': [113, 292, 317, 331, 365, 398, 450, 463, 515, 521, 533, 598, 599, 626, 837, 924], 'Petroleum Refining': [1, 2, 6, 12, 24, 76, 140, 148, 149, 154, 203, 344, 456, 501, 715, 733], 'Pharmaceuticals': [36, 55, 70, 117, 144, 145, 150, 194, 297, 368, 379, 537, 574, 663, 713, 789, 940], 'Pipelines': [52, 58, 66, 192, 236, 328, 405, 448, 632, 658, 664, 693, 740, 922, 957, 974], 'Publishing, Printing': [257, 330, 440, 530], 'Railroads': [122, 239, 255, 842], 'Real estate': [320, 477, 484, 487, 528, 697, 739, 813, 828, 847, 895, 931], 'Scientific,Photographic and Control Equipment': [146, 180, 388, 618, 674, 867, 896, 897, 939, 965], 'Securities': [266, 334, 355, 425, 434, 520, 564, 590, 619, 630, 679, 703, 726, 731, 807, 862, 935, 980, 999], 'Semiconductors and Other Electronic Components': [51, 189, 190, 232, 318, 339, 407, 431, 472, 552, 562, 721, 725, 768, 779, 794, 866, 868, 880, 900, 901, 926], 'Specialty Retailers: Apparel': [102, 187, 261, 268, 383, 531, 532, 536, 647, 700, 702, 705, 780, 818, 840, 843, 854, 865, 964], 'Specialty Retailers: Other': [17, 32, 49, 71, 132, 193, 201, 244, 259, 276, 293, 306, 310, 329, 364, 380, 381, 385, 392, 401, 422, 459, 473, 500, 543, 550, 596, 645, 649, 662, 668, 684, 708, 722, 760, 809, 860, 875, 909, 913, 923, 930, 988], 'Telecommunications': [11, 14, 42, 94, 129, 167, 207, 316, 400, 418, 451, 517, 539, 611, 650, 657, 883], 'Temporary Help': [143, 470, 551, 959], 'Tobacco': [101, 168, 336, 512, 853, 911], 'Toys, Sporting Goods': [438, 594], 'Transportation Equipment': [430, 432, 573, 615, 947], 'Transportation and Logistics': [224, 412, 455, 672, 908], 'Trucking, Truck Leasing': [406, 433, 509, 592, 718, 786, 796, 831, 970], 'Utilities: Gas and Electric': [110, 115, 162, 177, 181, 182, 183, 205, 225, 235, 240, 242, 245, 254, 256, 269, 273, 312, 366, 382, 403, 417, 437, 464, 518, 523, 525, 526, 682, 696, 709, 730, 752, 832, 835, 845, 881, 975, 977], 'Waste Management': [216, 322, 690, 849, 987], 'Wholesalers: Diversified': [67, 179, 198, 289, 298, 315, 359, 402, 410, 419, 444, 507, 508, 513, 547, 589, 623, 671, 759, 797, 879, 904, 916, 936], 'Wholesalers: Electronics and Office Equipment': [61, 106, 107, 130, 219, 488, 492, 774], 'Wholesalers: Food and Grocery': [60, 127, 351, 358, 396, 642], 'Wholesalers: Health Care': [10, 15, 25, 286, 308, 616], 'zMiscellaneous': [97, 361, 443, 460, 749, 753, 846, 951]}

In [24]:
df.iloc[5,:]

lon                         -83.0458
lat                          42.3314
company               General Motors
location                 Detroit, MI
industry    Motor Vehicles and Parts
state                             MI
city                         Detroit
Name: 5, dtype: object

In [32]:
industries.get_group('Motor Vehicles and Parts').sort_values('company')

,lon,lat,company,location,industry,state,city
973,-86.1581,39.7684,Allison Transmission Holdings,"Indianaoplis, IN",Motor Vehicles and Parts,IN,Indianaoplis
656,-83.0458,42.3314,American Axle & Manufacturing,"Detroit, MI",Motor Vehicles and Parts,MI,Detroit
311,-83.2341,42.6875,Autoliv,"Auburn Hills, MI",Motor Vehicles and Parts,MI,Auburn Hills
346,-83.2341,42.6875,BorgWarner,"Auburn Hills, MI",Motor Vehicles and Parts,MI,Auburn Hills
687,-83.6499,41.0442,Cooper Tire & Rubber,"Findlay, OH",Motor Vehicles and Parts,OH,Findlay
706,-83.4755,42.4806,Cooper-Standard Holdings,"Novi, MI",Motor Vehicles and Parts,MI,Novi
409,-83.6538,41.5628,Dana Holding,"Maumee, OH",Motor Vehicles and Parts,OH,Maumee
783,-84.3007,34.1322,Exide Technologies,"Milton, GA",Motor Vehicles and Parts,GA,Milton
8,-83.1763,42.3223,Ford Motor,"Dearborn, MI",Motor Vehicles and Parts,MI,Dearborn
5,-83.0458,42.3314,General Motors,"Detroit, MI",Motor Vehicles and Parts,MI,Detroit
165,-81.5190,41.0814,Goodyear Tire & Rubber,"Akron, OH",Motor Vehicles and Parts,OH,Akron
65,-87.9065,43.0389,Johnson Controls,"Milwaukee, WI",Motor Vehicles and Parts,WI,Milwaukee
173,-83.2219,42.4734,Lear,"Southfield, MI",Motor Vehicles and Parts,MI,Southfield
640,-83.1498,42.6064,Meritor,"Troy, MI",Motor Vehicles and Parts,MI,Troy
811,-83.4702,42.3714,Metaldyne Performance Group,"Plymouth, MI",Motor Vehicles and Parts,MI,Plymouth
275,-88.0748,41.8011,Navistar International,"Lisle, IL",Motor Vehicles and Parts,IL,Lisle
393,-88.5426,44.0247,Oshkosh,"Oshkosh, WI",Motor Vehicles and Parts,WI,Oshkosh
157,-122.2010,47.6104,Paccar,"Bellevue, WA",Motor Vehicles and Parts,WA,Bellevue
174,-83.3527,42.3684,TRW Automotive Holdings,"Livonia, MI",Motor Vehicles and Parts,MI,Livonia
340,-87.8406,42.2586,Tenneco,"Lake Forest, IL",Motor Vehicles and Parts,IL,Lake Forest
716,-122.1430,37.4419,Tesla Motors,"Palo Alto, CA",Motor Vehicles and Parts,CA,Palo Alto
667,-85.9767,41.6820,Thor Industries,"Elkhart, IN",Motor Vehicles and Parts,IN,Elkhart
955,-83.3527,42.3684,Tower International,"Livonia, MI",Motor Vehicles and Parts,MI,Livonia
343,-83.4838,42.2203,Visteon,"Van Buren Township, MI",Motor Vehicles and Parts,MI,Van Buren Township
784,-83.1499,42.6584,WABCO Holdings,"Rochester Hills, MI",Motor Vehicles and Parts,MI,Rochester Hills

In [34]:
industries.get_group('Motor Vehicles and Parts').shape

(25, 7)

In [42]:
type(industries.get_group('Motor Vehicles and Parts'))

pandas.core.frame.DataFrame