In [8]:
import  numpy as np
import pandas as pd

In [9]:
#Importing data using read_csv()
df=pd.read_csv("matches.csv")

In [10]:
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
# Important functions and attributes
df.head

<bound method NDFrame.head of       id  season       city        date                        team1  \
0      1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad
1      2    2017       Pune  2017-04-06               Mumbai Indians
2      3    2017     Rajkot  2017-04-07                Gujarat Lions
3      4    2017     Indore  2017-04-08       Rising Pune Supergiant
4      5    2017  Bangalore  2017-04-08  Royal Challengers Bangalore
..   ...     ...        ...         ...                          ...
631  632    2016     Raipur  2016-05-22             Delhi Daredevils
632  633    2016  Bangalore  2016-05-24                Gujarat Lions
633  634    2016      Delhi  2016-05-25          Sunrisers Hyderabad
634  635    2016      Delhi  2016-05-27                Gujarat Lions
635  636    2016  Bangalore  2016-05-29          Sunrisers Hyderabad

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field
1         Rising Pune Supergiant       Rising Pune Supergiant         field
2          Kolkata Knight Riders        Kolkata Knight Riders         field
3                Kings XI Punjab              Kings XI Punjab         field
4               Delhi Daredevils  Royal Challengers Bangalore           bat
..                           ...                          ...           ...
631  Royal Challengers Bangalore  Royal Challengers Bangalore         field
632  Royal Challengers Bangalore  Royal Challengers Bangalore         field
633        Kolkata Knight Riders        Kolkata Knight Riders         field
634          Sunrisers Hyderabad          Sunrisers Hyderabad         field
635  Royal Challengers Bangalore          Sunrisers Hyderabad           bat

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35
1    normal           0       Rising Pune Supergiant            0
2    normal           0        Kolkata Knight Riders            0
3    normal           0              Kings XI Punjab            0
4    normal           0  Royal Challengers Bangalore           15
..      ...         ...                          ...          ...
631  normal           0  Royal Challengers Bangalore            0
632  normal           0  Royal Challengers Bangalore            0
633  normal           0          Sunrisers Hyderabad           22
634  normal           0          Sunrisers Hyderabad            0
635  normal           0          Sunrisers Hyderabad            8

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh
1                 7       SPD Smith
2                10         CA Lynn
3                 6      GJ Maxwell
4                 0       KM Jadhav
..              ...             ...
631               6         V Kohli
632               4  AB de Villiers
633               0    MC Henriques
634               4       DA Warner
635               0     BCJ Cutting

                                                venue          umpire1  \
0           Rajiv Gandhi International Stadium, Uppal      AY Dandekar
1             Maharashtra Cricket Association Stadium   A Nand Kishore
2              Saurashtra Cricket Association Stadium      Nitin Menon
3                              Holkar Cricket Stadium     AK Chaudhary
4                               M Chinnaswamy Stadium              NaN
..                                                ...              ...
631  Shaheed Veer Narayan Singh International Stadium   A Nand Kishore
632                             M Chinnaswamy Stadium     AK Chaudhary
633                                  Feroz Shah Kotla        M Erasmus
634                                  Feroz Shah Kotla        M Erasmus
635                             M Chinnaswamy Stadium  HDPK Dharmasena

             umpire2  umpire3
0           NJ Llong      NaN
1             S Ravi      NaN
2          CK Nandan      NaN
3      C Shamshuddin      NaN
4                NaN      NaN
..               ...      ...
631     BNJ Oxenford      NaN
632  HDPK Dharmasena      NaN
633    C Shamshuddin      NaN
634        CK Nandan      NaN
635     BNJ Oxenford      NaN

[636 rows x 18 columns]>

In [13]:
df.head(10)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
6,7,2017,Mumbai,2017-04-09,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
7,8,2017,Indore,2017-04-10,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
9,10,2017,Mumbai,2017-04-12,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN

In [14]:
df.tail()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [15]:
df.tail

<bound method NDFrame.tail of       id  season       city        date                        team1  \
0      1    2017  Hyderabad  2017-04-05          Sunrisers Hyderabad
1      2    2017       Pune  2017-04-06               Mumbai Indians
2      3    2017     Rajkot  2017-04-07                Gujarat Lions
3      4    2017     Indore  2017-04-08       Rising Pune Supergiant
4      5    2017  Bangalore  2017-04-08  Royal Challengers Bangalore
..   ...     ...        ...         ...                          ...
631  632    2016     Raipur  2016-05-22             Delhi Daredevils
632  633    2016  Bangalore  2016-05-24                Gujarat Lions
633  634    2016      Delhi  2016-05-25          Sunrisers Hyderabad
634  635    2016      Delhi  2016-05-27                Gujarat Lions
635  636    2016  Bangalore  2016-05-29          Sunrisers Hyderabad

                           team2                  toss_winner toss_decision  \
0    Royal Challengers Bangalore  Royal Challengers Bangalore         field
1         Rising Pune Supergiant       Rising Pune Supergiant         field
2          Kolkata Knight Riders        Kolkata Knight Riders         field
3                Kings XI Punjab              Kings XI Punjab         field
4               Delhi Daredevils  Royal Challengers Bangalore           bat
..                           ...                          ...           ...
631  Royal Challengers Bangalore  Royal Challengers Bangalore         field
632  Royal Challengers Bangalore  Royal Challengers Bangalore         field
633        Kolkata Knight Riders        Kolkata Knight Riders         field
634          Sunrisers Hyderabad          Sunrisers Hyderabad         field
635  Royal Challengers Bangalore          Sunrisers Hyderabad           bat

     result  dl_applied                       winner  win_by_runs  \
0    normal           0          Sunrisers Hyderabad           35
1    normal           0       Rising Pune Supergiant            0
2    normal           0        Kolkata Knight Riders            0
3    normal           0              Kings XI Punjab            0
4    normal           0  Royal Challengers Bangalore           15
..      ...         ...                          ...          ...
631  normal           0  Royal Challengers Bangalore            0
632  normal           0  Royal Challengers Bangalore            0
633  normal           0          Sunrisers Hyderabad           22
634  normal           0          Sunrisers Hyderabad            0
635  normal           0          Sunrisers Hyderabad            8

     win_by_wickets player_of_match  \
0                 0    Yuvraj Singh
1                 7       SPD Smith
2                10         CA Lynn
3                 6      GJ Maxwell
4                 0       KM Jadhav
..              ...             ...
631               6         V Kohli
632               4  AB de Villiers
633               0    MC Henriques
634               4       DA Warner
635               0     BCJ Cutting

                                                venue          umpire1  \
0           Rajiv Gandhi International Stadium, Uppal      AY Dandekar
1             Maharashtra Cricket Association Stadium   A Nand Kishore
2              Saurashtra Cricket Association Stadium      Nitin Menon
3                              Holkar Cricket Stadium     AK Chaudhary
4                               M Chinnaswamy Stadium              NaN
..                                                ...              ...
631  Shaheed Veer Narayan Singh International Stadium   A Nand Kishore
632                             M Chinnaswamy Stadium     AK Chaudhary
633                                  Feroz Shah Kotla        M Erasmus
634                                  Feroz Shah Kotla        M Erasmus
635                             M Chinnaswamy Stadium  HDPK Dharmasena

             umpire2  umpire3
0           NJ Llong      NaN
1             S Ravi      NaN
2          CK Nandan      NaN
3      C Shamshuddin      NaN
4                NaN      NaN
..               ...      ...
631     BNJ Oxenford      NaN
632  HDPK Dharmasena      NaN
633    C Shamshuddin      NaN
634        CK Nandan      NaN
635     BNJ Oxenford      NaN

[636 rows x 18 columns]>

In [16]:
df.dtypes

id                   int64
season               int64
city                object
date                object
team1               object
team2               object
toss_winner         object
toss_decision       object
result              object
dl_applied           int64
winner              object
win_by_runs          int64
win_by_wickets       int64
player_of_match     object
venue               object
umpire1             object
umpire2             object
umpire3            float64
dtype: object

In [17]:
df.shape

(636, 18)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 636 entries, 0 to 635
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               636 non-null    int64
 1   season           636 non-null    int64
 2   city             629 non-null    object
 3   date             636 non-null    object
 4   team1            636 non-null    object
 5   team2            636 non-null    object
 6   toss_winner      636 non-null    object
 7   toss_decision    636 non-null    object
 8   result           636 non-null    object
 9   dl_applied       636 non-null    int64
 10  winner           633 non-null    object
 11  win_by_runs      636 non-null    int64
 12  win_by_wickets   636 non-null    int64
 13  player_of_match  633 non-null    object
 14  venue            636 non-null    object
 15  umpire1          635 non-null    object
 16  umpire2          635 non-null    object
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), object(12)
memory usage: 89.6+ KB

In [19]:
df.describe()

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,636.000000,636.000000,636.000000,636.000000,636.000000,0.0
mean,318.500000,2012.490566,0.025157,13.682390,3.372642,NaN
std,183.741666,2.773026,0.156726,23.908877,3.420338,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,159.750000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,318.500000,2012.000000,0.000000,0.000000,4.000000,NaN
75%,477.250000,2015.000000,0.000000,20.000000,7.000000,NaN
max,636.000000,2017.000000,1.000000,146.000000,10.000000,NaN

In [20]:
#Fetching rows and columns using iloc
df['winner']

0              Sunrisers Hyderabad
1           Rising Pune Supergiant
2            Kolkata Knight Riders
3                  Kings XI Punjab
4      Royal Challengers Bangalore
                  ...
631    Royal Challengers Bangalore
632    Royal Challengers Bangalore
633            Sunrisers Hyderabad
634            Sunrisers Hyderabad
635            Sunrisers Hyderabad
Name: winner, Length: 636, dtype: object

In [21]:
type(df['winner'])

pandas.core.series.Series

In [22]:
df[['team1','team2','winner']]

,team1,team2,winner
0,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad
1,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant
2,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders
3,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab
4,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore
...,...,...,...
631,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore
632,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore
633,Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad
634,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad
635,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad

In [23]:
df[['team1','team2','winner']].shape

(636, 3)

In [24]:
type(df[['team1','team2','winner']])

pandas.core.frame.DataFrame

In [25]:
df.iloc[1:4]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN

In [26]:
df.iloc[1:11:2]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
7,8,2017,Indore,2017-04-10,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
9,10,2017,Mumbai,2017-04-12,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN

In [27]:
df.iloc[[5,8,77]]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
77,78,2008,Jaipur,2008-05-01,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,normal,0,Rajasthan Royals,45,0,SA Asnodkar,Sawai Mansingh Stadium,RE Koertzen,GA Pratapkumar,NaN

In [28]:
df.iloc[:,[5,6,10]]

,team2,toss_winner,winner
0,Royal Challengers Bangalore,Royal Challengers Bangalore,Sunrisers Hyderabad
1,Rising Pune Supergiant,Rising Pune Supergiant,Rising Pune Supergiant
2,Kolkata Knight Riders,Kolkata Knight Riders,Kolkata Knight Riders
3,Kings XI Punjab,Kings XI Punjab,Kings XI Punjab
4,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore
...,...,...,...
631,Royal Challengers Bangalore,Royal Challengers Bangalore,Royal Challengers Bangalore
632,Royal Challengers Bangalore,Royal Challengers Bangalore,Royal Challengers Bangalore
633,Kolkata Knight Riders,Kolkata Knight Riders,Sunrisers Hyderabad
634,Sunrisers Hyderabad,Sunrisers Hyderabad,Sunrisers Hyderabad
635,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad

In [29]:
df.iloc[[45,78,99],:]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
45,46,2017,Chandigarh,2017-05-07,Kings XI Punjab,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,6,DR Smith,"Punjab Cricket Association IS Bindra Stadium, ...",A Nand Kishore,VK Sharma,NaN
78,79,2008,Chennai,2008-05-02,Chennai Super Kings,Delhi Daredevils,Chennai Super Kings,bat,normal,0,Delhi Daredevils,0,8,V Sehwag,"MA Chidambaram Stadium, Chepauk",BF Bowden,K Hariharan,NaN
99,100,2008,Delhi,2008-05-17,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,1,Kings XI Punjab,6,0,DPMD Jayawardene,Feroz Shah Kotla,AV Jayaprakash,RE Koertzen,NaN

In [30]:
df.iloc[50,[4,5,6,10]]

team1                Delhi Daredevils
team2          Rising Pune Supergiant
toss_winner          Delhi Daredevils
winner               Delhi Daredevils
Name: 50, dtype: object

In [31]:
#Filtering dataframe on a condition | Masking using boolean series
mask=df['city']=='Pune'
df[mask].shape

(32, 18)

In [32]:
df[mask]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
24,25,2017,Pune,2017-04-22,Sunrisers Hyderabad,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,6,MS Dhoni,Maharashtra Cricket Association Stadium,AY Dandekar,A Deshmukh,NaN
28,29,2017,Pune,2017-04-26,Rising Pune Supergiant,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,RV Uthappa,Maharashtra Cricket Association Stadium,AY Dandekar,NJ Llong,NaN
32,33,2017,Pune,2017-04-29,Rising Pune Supergiant,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Rising Pune Supergiant,61,0,LH Ferguson,Maharashtra Cricket Association Stadium,KN Ananthapadmanabhan,M Erasmus,NaN
37,38,2017,Pune,2017-05-01,Gujarat Lions,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,5,BA Stokes,Maharashtra Cricket Association Stadium,M Erasmus,C Shamshuddin,NaN
53,54,2017,Pune,2017-05-14,Kings XI Punjab,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,9,JD Unadkat,Maharashtra Cricket Association Stadium,AY Dandekar,A Deshmukh,NaN
314,315,2012,Pune,2012-04-08,Pune Warriors,Kings XI Punjab,Pune Warriors,bat,normal,0,Pune Warriors,22,0,MN Samuels,Subrata Roy Sahara Stadium,S Das,SJA Taufel,NaN
323,324,2012,Pune,2012-04-14,Chennai Super Kings,Pune Warriors,Chennai Super Kings,bat,normal,0,Pune Warriors,0,7,JD Ryder,Subrata Roy Sahara Stadium,Aleem Dar,BNJ Oxenford,NaN
338,339,2012,Pune,2012-04-24,Pune Warriors,Delhi Daredevils,Pune Warriors,bat,normal,0,Delhi Daredevils,0,8,V Sehwag,Subrata Roy Sahara Stadium,S Ravi,RJ Tucker,NaN
340,341,2012,Pune,2012-04-26,Deccan Chargers,Pune Warriors,Deccan Chargers,bat,normal,0,Deccan Chargers,18,0,CL White,Subrata Roy Sahara Stadium,S Ravi,RJ Tucker,NaN
350,351,2012,Pune,2012-05-03,Mumbai Indians,Pune Warriors,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,SL Malinga,Subrata Roy Sahara Stadium,Asad Rauf,S Asnani,NaN
357,358,2012,Pune,2012-05-08,Pune Warriors,Rajasthan Royals,Pune Warriors,bat,normal,0,Rajasthan Royals,0,7,SR Watson,Subrata Roy Sahara Stadium,Asad Rauf,BR Doctrove,NaN
361,362,2012,Pune,2012-05-11,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,normal,0,Royal Challengers Bangalore,35,0,CH Gayle,Subrata Roy Sahara Stadium,BF Bowden,SK Tarapore,NaN
374,375,2012,Pune,2012-05-19,Kolkata Knight Riders,Pune Warriors,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,34,0,Shakib Al Hasan,Subrata Roy Sahara Stadium,S Asnani,BR Doctrove,NaN
377,378,2012,Pune,2012-05-22,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,18,0,YK Pathan,Subrata Roy Sahara Stadium,BR Doctrove,SJA Taufel,NaN
386,387,2013,Pune,2013-04-07,Pune Warriors,Kings XI Punjab,Pune Warriors,bat,normal,0,Kings XI Punjab,0,8,M Vohra,Subrata Roy Sahara Stadium,S Asnani,SJA Taufel,NaN
392,393,2013,Pune,2013-04-11,Rajasthan Royals,Pune Warriors,Rajasthan Royals,bat,normal,0,Pune Warriors,0,7,AJ Finch,Subrata Roy Sahara Stadium,M Erasmus,K Srinath,NaN
401,402,2013,Pune,2013-04-17,Sunrisers Hyderabad,Pune Warriors,Pune Warriors,field,normal,0,Sunrisers Hyderabad,11,0,A Mishra,Subrata Roy Sahara Stadium,Asad Rauf,AK Chaudhary,NaN
421,422,2013,Pune,2013-04-30,Chennai Super Kings,Pune Warriors,Chennai Super Kings,bat,normal,0,Chennai Super Kings,37,0,MS Dhoni,Subrata Roy Sahara Stadium,S Das,SJA Taufel,NaN
425,426,2013,Pune,2013-05-02,Royal Challengers Bangalore,Pune Warriors,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,17,0,AB de Villiers,Subrata Roy Sahara Stadium,Aleem Dar,C Shamshuddin,NaN
436,437,2013,Pune,2013-05-09,Kolkata Knight Riders,Pune Warriors,Kolkata Knight Riders,bat,normal,0,Kolkata Knight Riders,46,0,G Gambhir,Subrata Roy Sahara Stadium,Asad Rauf,S Asnani,NaN
438,439,2013,Pune,2013-05-11,Pune Warriors,Mumbai Indians,Pune Warriors,bat,normal,0,Mumbai Indians,0,5,MG Johnson,Subrata Roy Sahara Stadium,Asad Rauf,AK Chaudhary,NaN
450,451,2013,Pune,2013-05-19,Pune Warriors,Delhi Daredevils,Pune Warriors,bat,normal,0,Pune Warriors,38,0,LJ Wright,Subrata Roy Sahara Stadium,NJ Llong,SJA Taufel,NaN
519,520,2015,Pune,2015-04-10,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,normal,0,Rajasthan Royals,26,0,JP Faulkner,Maharashtra Cricket Association Stadium,SD Fry,CB Gaffaney,NaN
527,528,2015,Pune,2015-04-15,Kings XI Punjab,Delhi Daredevils,Kings XI Punjab,bat,normal,0,Delhi Daredevils,0,5,MA Agarwal,Maharashtra Cricket Association Stadium,CB Gaffaney,K Srinath,NaN
531,532,2015,Pune,2015-04-18,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,4,AD Russell,Maharashtra Cricket Association Stadium,SD Fry,CK Nandan,NaN
573,574,2015,Pune,2015-05-20,Royal Challengers Bangalore,Rajasthan Royals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,71,0,AB de Villiers,Maharashtra Cricket Association Stadium,AK Chaudhary,C Shamshuddin,NaN
591,592,2016,Pune,2016-04-22,Royal Challengers Bangalore,Rising Pune Supergiants,Rising Pune Supergiants,field,normal,0,Royal Challengers Bangalore,13,0,AB de Villiers,Maharashtra Cricket Association Stadium,CB Gaffaney,VK Sharma,NaN
595,596,2016,Pune,2016-04-24,Rising Pune Supergiants,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,2,SA Yadav,Maharashtra Cricket Association Stadium,CB Gaffaney,A Nand Kishore,NaN
600,601,2016,Pune,2016-04-29,Rising Pune Supergiants,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,3,DR Smith,Maharashtra Cricket Association Stadium,CB Gaffaney,BNJ Oxenford,NaN
604,605,2016,Pune,2016-05-01,Rising Pune Supergiants,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,RG Sharma,Maharashtra Cricket Association Stadium,AY Dandekar,RJ Tucker,NaN

In [33]:
def get_city_count(city):
    mask=df['city']==city
    return df[mask].shape[0]

In [34]:
get_city_count('Pune')

32

In [35]:
mask1=df['city']=='Jaipur'
mask2=df['date']=='2008-05-01'

In [36]:
df[mask1 & mask2]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
77,78,2008,Jaipur,2008-05-01,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals,bat,normal,0,Rajasthan Royals,45,0,SA Asnodkar,Sawai Mansingh Stadium,RE Koertzen,GA Pratapkumar,NaN

In [37]:
#Vlaue_Coubts Function
df['winner'].value_counts()

winner
Mumbai Indians                 92
Chennai Super Kings            79
Kolkata Knight Riders          77
Royal Challengers Bangalore    73
Kings XI Punjab                70
Rajasthan Royals               63
Delhi Daredevils               62
Sunrisers Hyderabad            42
Deccan Chargers                29
Gujarat Lions                  13
Pune Warriors                  12
Rising Pune Supergiant         10
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: count, dtype: int64

In [38]:
#Droping Duplicates
#df['city'].drop_duplicates()
df.drop_duplicates(subset=['city']).shape

(31, 18)

In [39]:
df.drop_duplicates('season' , keep='last')[['season','winner']].sort_values('season')

     season                 winner
116    2008       Rajasthan Royals
173    2009        Deccan Chargers
233    2010    Chennai Super Kings
306    2011    Chennai Super Kings
380    2012  Kolkata Knight Riders
456    2013         Mumbai Indians
516    2014  Kolkata Knight Riders
575    2015         Mumbai Indians
635    2016    Sunrisers Hyderabad
58     2017         Mumbai Indians

In [40]:
grp=df.groupby('team1')

In [41]:
type(grp)

pandas.core.groupby.generic.DataFrameGroupBy

In [42]:
grp

In [43]:
grp.sum()

,id,season,city,date,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
team1,,,,,,,,,,,,,,,,,
Chennai Super Kings,24170,154885,ChandigarhChennaiBangaloreChennaiJaipurChennai...,2008-04-192008-04-232008-04-282008-05-022008-0...,Kings XI PunjabMumbai IndiansRoyal Challengers...,Chennai Super KingsMumbai IndiansChennai Super...,batfieldbatbatbatfieldfieldfieldfieldbatfieldf...,normalnormalnormalnormalnormalnormalnormalnorm...,3,Chennai Super KingsChennai Super KingsChennai ...,1594,192,MEK HusseyML HaydenMS DhoniV SehwagSohail Tanv...,"Punjab Cricket Association Stadium, MohaliMA C...",MR BensonDJ HarperBR DoctroveBF BowdenAsad Rau...,SL ShastriGA PratapkumarRB TiffinK HariharanAV...,0.0
Deccan Chargers,9425,86437,KolkataHyderabadHyderabadHyderabadHyderabadJai...,2008-04-202008-04-222008-04-242008-05-012008-0...,Kolkata Knight RidersDelhi DaredevilsRajasthan...,Deccan ChargersDeccan ChargersRajasthan Royals...,batbatfieldfieldbatfieldfieldbatbatbatfieldbat...,normalnormalnormalnormalnormalnormalnormalnorm...,0,Kolkata Knight RidersDelhi DaredevilsRajasthan...,421,148,DJ HusseyV SehwagYK PathanSE MarshR Vinay Kuma...,Eden GardensRajiv Gandhi International Stadium...,BF BowdenIL HowellAsad RaufBR DoctroveAsad Rau...,K HariharanAM SahebaMR BensonRB TiffinRE Koert...,0.0
Delhi Daredevils,19979,126788,PuneDelhiDelhiKolkataChandigarhDelhiChandigarh...,2017-04-112017-04-152017-04-172017-04-282017-0...,Rising Pune SupergiantKings XI PunjabKolkata K...,Rising Pune SupergiantDelhi DaredevilsDelhi Da...,fieldbatbatfieldfieldbatbatfieldfieldfieldfiel...,normalnormalnormalnormalnormalnormalnormalnorm...,3,Delhi DaredevilsDelhi DaredevilsKolkata Knight...,596,232,SV SamsonCJ AndersonNM Coulter-NileG GambhirSa...,Maharashtra Cricket Association StadiumFeroz S...,AY DandekarYC BardeNitin MenonNJ LlongYC Barde...,S RaviNitin MenonCK NandanS RaviCK NandanCK Na...,0.0
Gujarat Lions,3914,28232,RajkotHyderabadMumbaiRajkotPuneDelhiKanpurKanp...,2017-04-072017-04-092017-04-162017-04-292017-0...,Kolkata Knight RidersSunrisers HyderabadMumbai...,Kolkata Knight RidersSunrisers HyderabadMumbai...,fieldfieldfieldbatfieldfieldfieldfieldfieldfie...,normalnormalnormaltienormalnormalnormalnormaln...,0,Kolkata Knight RidersSunrisers HyderabadMumbai...,1,78,CA LynnRashid KhanN RanaKH PandyaBA StokesRR P...,Saurashtra Cricket Association StadiumRajiv Ga...,Nitin MenonA DeshmukhA Nand KishoreAK Chaudhar...,CK NandanNJ LlongS RaviCB GaffaneyC Shamshuddi...,0.0
Kings XI Punjab,24966,154976,KolkataIndoreRajkotBangaloreChandigarhChandiga...,2017-04-132017-04-202017-04-232017-05-052017-0...,Kolkata Knight RidersMumbai IndiansGujarat Lio...,Kolkata Knight RidersMumbai IndiansGujarat Lio...,fieldfieldfieldfieldfieldfieldfieldfieldbatfie...,normalnormalnormalnormalnormalnormalnormalnorm...,2,Kolkata Knight RidersMumbai IndiansKings XI Pu...,867,278,SP NarineJC ButtlerHM AmlaSandeep SharmaDR Smi...,Eden GardensHolkar Cricket StadiumSaurashtra C...,A DeshmukhM ErasmusAK ChaudharyCB GaffaneyA Na...,NJ LlongC ShamshuddinM ErasmusC ShamshuddinVK ...,0.0
Kochi Tuskers Kerala,1848,14077,KochiMumbaiKolkataJaipurKochiBangaloreIndore,2011-04-092011-04-132011-04-202011-04-242011-0...,Royal Challengers BangalorePune WarriorsKolkat...,Kochi Tuskers KeralaKochi Tuskers KeralaKolkat...,batbatfieldfieldfieldbatfield,normalnormalnormalnormalnormalnormalnormal,0,Royal Challengers BangalorePune WarriorsKochi ...,23,33,AB de VilliersMD MishraDPMD JayawardeneSK Warn...,Nehru StadiumDr DY Patil Sports AcademyEden Ga...,HDPK DharmasenaS AsnaniAleem DarBR DoctroveS R...,K HariharanPR ReiffelRB TiffinSK TaraporeRJ Tu...,0.0
Kolkata Knight Riders,20139,136823,MumbaiKolkataKolkataKolkataKolkataBangaloreBan...,2017-04-092017-04-152017-04-212017-04-232017-0...,Mumbai IndiansSunrisers HyderabadGujarat Lions...,Mumbai IndiansSunrisers HyderabadGujarat Lions...,fieldfieldfieldfieldfieldfieldfieldbatbatbatba...,normalnormalnormalnormalnormalnormalnormalnorm...,2,Mumbai IndiansKolkata Knight RidersGujarat Lio...,879,236,N RanaRV UthappaSK RainaNM Coulter-NileRA Trip...,Wankhede StadiumEden GardensEden GardensEden G...,Nitin MenonAY DandekarCB GaffaneyCB GaffaneyKN...,CK NandanNJ LlongNitin MenonCK NandanA Nand Ki...,0.0
Mumbai Indians,27142,165023,PuneMumbaiDelhiHyderabadKolkataHyderabadMumbai...,2017-04-062017-04-222017-05-062017-05-082017-0...,Rising Pune SupergiantDelhi DaredevilsDelhi Da...,Rising Pune SupergiantDelhi DaredevilsDelhi Da...,fieldfieldfieldbatfieldbatbatfieldfieldfieldfi...,normalnormalnormalnormalnormalnormalnormalnorm...,0,Rising Pune SupergiantMumbai IndiansMumbai Ind...,1532,240,SPD SmithMJ McClenaghanLMP SimmonsS DhawanAT R...,Maharashtra Cricket Association StadiumWankhed...,A Nand KishoreA Nand KishoreNitin MenonKN Anan...,S RaviS RaviCK NandanM ErasmusS RaviS RaviDJ H...,0.0
Pune Warriors,6900,40241,MumbaiMumbaiMumbaiJaipurMumbaiMumbaiMumbaiPune...,2011-04-172011-04-202011-04-272011-05-012011-0...,Delhi DaredevilsMumbai IndiansChennai Super Ki...,Delhi DaredevilsPune WarriorsPune WarriorsRaja...,fieldbatbatfieldfieldfieldfieldbatfieldbatfiel...,normalnormalnormalnormalnormalnormalnormalnorm...,0,Delhi DaredevilsMumbai IndiansChennai Super Ki...,139,90,Yuvraj SinghMM PatelDE BollingerLRPL TaylorA M...,Dr DY Patil Sports AcademyWankhede StadiumDr D...,Asad RaufAsad RaufAsad RaufSK TaraporeS RaviS ...,AM SahebaAM SahebaSL ShastriSJA TaufelSK Tarap...,0.0
Rajasthan Royals,16962,108623,DelhiJaipurMumbaiJaipurChennaiMumbaiCape TownD...,2008-04-192008-05-012008-05-072008-05-172008-0...,Delhi DaredevilsKolkata Knight RidersMumbai In...,Rajasthan RoyalsRajasthan RoyalsMumbai Indians...,batbatfieldfieldbatfieldfieldfieldbatbatfieldf...,normalnormalnormalnormalnormalnormaltienormaln...,0,Delhi DaredevilsRajasthan RoyalsMumbai Indians...,821,192,MF MaharoofSA AsnodkarA NehraGC SmithJA Morkel...,Feroz Shah KotlaSawai Mansingh StadiumDr DY Pa...,Aleem DarRE KoertzenDJ HarperBF BowdenDJ Harpe...,GA PratapkumarGA PratapkumarRE KoertzenSL Shas...,0.0
Rising Pune Supergiant,223,16136,IndoreRajkotBangaloreMumbaiPunePuneHyderabadMu...,2017-04-082017-04-142017-04-162017-04-242017-0...,Kings XI PunjabGujarat LionsRoyal Challengers ...,Kings XI PunjabGujarat LionsRoyal Challengers ...,fieldfieldfieldfieldfieldfieldfieldfield,normalnormalnormalnormalnormalnormalnormalnormal,0,Kings XI PunjabGujarat LionsRising Pune Superg...,123,20,GJ MaxwellAJ TyeBA StokesBA StokesRV UthappaLH...,Holkar Cricket StadiumSaurashtra Cricket Assoc...,AK ChaudharyA Nand KishoreKN Ananthapadmanabha...,C ShamshuddinS RaviC ShamshuddinS RaviNJ Llong...,0.0
Rising Pune Supergiants,4202,14112,RajkotChandigarhPunePunePuneBangaloreKolkata,2016-04-142016-04-172016-04-242016-04-292016-0...,Gujarat LionsKings XI PunjabKolkata Knight Rid...,Rising Pune SupergiantsRising Pune Supergiants...,batbatfieldfieldfieldfieldbat,normalnormalnormalnormalnormalnormalnormal,1,Gujarat LionsKings XI PunjabKolkata Knight Rid...,0,41,AJ FinchM VohraSA YadavDR SmithRG SharmaV Kohl...,Saurashtra Cricket Association StadiumPunjab C...,VA KulkarniS RaviCB GaffaneyCB GaffaneyAY Dand...,CK NandanC ShamshuddinA Nand KishoreBNJ Oxenfo...,0.0
Royal Challengers Bangalore,23257,140902,BangaloreIndoreBangaloreRajkotBangaloreMumbaiB...,2017-04-082017-04-102017-04-142017-04-182017-0...,Delhi DaredevilsKings XI PunjabMumbai IndiansG...,Royal Challengers BangaloreRoyal Challengers B...,batbatfieldfieldfieldbatfieldbatfieldfieldfiel...,normalnormalnormalnormalnormalnormalnormalnorm...,1,Royal Challengers BangaloreKings XI PunjabMumb...,1196,232,KM JadhavAR PatelKA PollardCH GayleAJ TyeRG Sh...,M Chinnaswamy StadiumHolkar Cricket StadiumM C...,AK ChaudharyKN AnanthapadmanabhanS RaviAK Chau...,C ShamshuddinAK ChaudharyVK SharmaC Shamshuddi...,0.0
Sunrisers Hyderabad,19439,92689,HyderabadMumbaiHyderabadHyderabadPuneChandigar...,2017-04-052017-04-122017-04-172017-04-192017-0...,Royal Challengers BangaloreMumbai IndiansKings...,Royal Challengers BangaloreMumbai IndiansKings...,fieldfieldfieldbatfieldfieldfieldfieldfieldfie...,normalnormalnormalnormalnormalnormalnormalnorm...,4,Sunrisers HyderabadMumbai IndiansSunrisers Hyd...,510,133,Yuvraj SinghJJ BumrahB KumarKS WilliamsonMS Dh...,"Rajiv Gandhi International Stadium, UppalWankh...",AY DandekarNitin MenonAY DandekarCB GaffaneyAY...,NJ LlongCK NandanA DeshmukhNJ LlongA DeshmukhC...,0.0

In [44]:
len(df)

636

In [45]:
len(grp)

14

In [47]:
grp['win_by_runs'].mean()

team1
Chennai Super Kings            20.701299
Deccan Chargers                 9.790698
Delhi Daredevils                9.460317
Gujarat Lions                   0.071429
Kings XI Punjab                11.259740
Kochi Tuskers Kerala            3.285714
Kolkata Knight Riders          12.926471
Mumbai Indians                 18.682927
Pune Warriors                   6.950000
Rajasthan Royals               15.203704
Rising Pune Supergiant         15.375000
Rising Pune Supergiants         0.000000
Royal Challengers Bangalore    17.085714
Sunrisers Hyderabad            11.086957
Name: win_by_runs, dtype: float64

In [48]:
grp.first()

,id,season,city,date,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
team1,,,,,,,,,,,,,,,,,
Chennai Super Kings,61,2008,Chandigarh,2008-04-19,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN
Deccan Chargers,64,2008,Kolkata,2008-04-20,Kolkata Knight Riders,Deccan Chargers,bat,normal,0,Kolkata Knight Riders,0,5,DJ Hussey,Eden Gardens,BF Bowden,K Hariharan,NaN
Delhi Daredevils,9,2017,Pune,2017-04-11,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
Gujarat Lions,3,2017,Rajkot,2017-04-07,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
Kings XI Punjab,11,2017,Kolkata,2017-04-13,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN
Kochi Tuskers Kerala,237,2011,Kochi,2011-04-09,Royal Challengers Bangalore,Kochi Tuskers Kerala,bat,normal,0,Royal Challengers Bangalore,0,6,AB de Villiers,Nehru Stadium,HDPK Dharmasena,K Hariharan,NaN
Kolkata Knight Riders,7,2017,Mumbai,2017-04-09,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
Mumbai Indians,2,2017,Pune,2017-04-06,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
Pune Warriors,250,2011,Mumbai,2011-04-17,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,3,Yuvraj Singh,Dr DY Patil Sports Academy,Asad Rauf,AM Saheba,NaN
Rajasthan Royals,62,2008,Delhi,2008-04-19,Delhi Daredevils,Rajasthan Royals,bat,normal,0,Delhi Daredevils,0,9,MF Maharoof,Feroz Shah Kotla,Aleem Dar,GA Pratapkumar,NaN
Rising Pune Supergiant,4,2017,Indore,2017-04-08,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
Rising Pune Supergiants,582,2016,Rajkot,2016-04-14,Gujarat Lions,Rising Pune Supergiants,bat,normal,0,Gujarat Lions,0,7,AJ Finch,Saurashtra Cricket Association Stadium,VA Kulkarni,CK Nandan,NaN
Royal Challengers Bangalore,5,2017,Bangalore,2017-04-08,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,AK Chaudhary,C Shamshuddin,NaN
Sunrisers Hyderabad,1,2017,Hyderabad,2017-04-05,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

In [49]:
grp.last()

,id,season,city,date,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
team1,,,,,,,,,,,,,,,,,
Chennai Super Kings,565,2015,Raipur,2015-05-12,Delhi Daredevils,Chennai Super Kings,bat,normal,0,Delhi Daredevils,0,6,Z Khan,Shaheed Veer Narayan Singh International Stadium,RK Illingworth,VA Kulkarni,NaN
Deccan Chargers,376,2012,Hyderabad,2012-05-20,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Deccan Chargers,9,0,DW Steyn,"Rajiv Gandhi International Stadium, Uppal",S Ravi,SJA Taufel,NaN
Delhi Daredevils,632,2016,Raipur,2016-05-22,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
Gujarat Lions,635,2016,Delhi,2016-05-27,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
Kings XI Punjab,629,2016,Visakhapatnam,2016-05-21,Rising Pune Supergiants,Kings XI Punjab,bat,normal,0,Rising Pune Supergiants,0,4,MS Dhoni,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,HDPK Dharmasena,Nitin Menon,NaN
Kochi Tuskers Kerala,290,2011,Indore,2011-05-13,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,KD Karthik,Holkar Cricket Stadium,S Asnani,RJ Tucker,NaN
Kolkata Knight Riders,631,2016,Kolkata,2016-05-22,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,22,0,YK Pathan,Eden Gardens,KN Ananthapadmanabhan,M Erasmus,NaN
Mumbai Indians,630,2016,Kanpur,2016-05-21,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,6,SK Raina,Green Park,AK Chaudhary,CK Nandan,NaN
Pune Warriors,451,2013,Pune,2013-05-19,Delhi Daredevils,Pune Warriors,bat,normal,0,Pune Warriors,38,0,LJ Wright,Subrata Roy Sahara Stadium,NJ Llong,SJA Taufel,NaN
Rajasthan Royals,570,2015,Mumbai,2015-05-16,Kolkata Knight Riders,Rajasthan Royals,bat,normal,0,Rajasthan Royals,9,0,SR Watson,Brabourne Stadium,RM Deshpande,RK Illingworth,NaN
Rising Pune Supergiant,56,2017,Mumbai,2017-05-16,Mumbai Indians,Mumbai Indians,field,normal,0,Rising Pune Supergiant,20,0,Washington Sundar,Wankhede Stadium,S Ravi,C Shamshuddin,NaN
Rising Pune Supergiants,621,2016,Kolkata,2016-05-14,Kolkata Knight Riders,Rising Pune Supergiants,bat,normal,1,Kolkata Knight Riders,0,8,YK Pathan,Eden Gardens,A Nand Kishore,BNJ Oxenford,NaN
Royal Challengers Bangalore,626,2016,Bangalore,2016-05-18,Kings XI Punjab,Kings XI Punjab,field,normal,1,Royal Challengers Bangalore,82,0,V Kohli,M Chinnaswamy Stadium,KN Ananthapadmanabhan,M Erasmus,NaN
Sunrisers Hyderabad,636,2016,Bangalore,2016-05-29,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [50]:
grp.groups

{'Chennai Super Kings': [60, 66, 73, 78, 82, 84, 90, 95, 116, 121, 130, 136, 140, 143, 148, 158, 165, 168, 172, 181, 193, 205, 210, 215, 223, 231, 233, 234, 242, 247, 251, 261, 271, 280, 284, 288, 296, 301, 306, 307, 312, 317, 323, 331, 346, 351, 354, 370, 378, 379, 380, 403, 417, 421, 424, 434, 441, 445, 453, 459, 464, 466, 477, 498, 503, 506, 518, 520, 526, 532, 537, 541, 546, 553, 558, 562, 564], 'Deccan Chargers': [63, 65, 67, 76, 79, 88, 107, 113, 123, 127, 135, 139, 146, 150, 154, 173, 178, 185, 188, 194, 219, 228, 232, 235, 244, 248, 252, 264, 278, 285, 291, 299, 315, 322, 327, 330, 336, 340, 345, 347, 355, 365, 375], 'Delhi Daredevils': [8, 14, 17, 30, 34, 50, 72, 75, 86, 92, 97, 99, 124, 132, 157, 160, 164, 166, 171, 184, 196, 199, 202, 208, 217, 237, 240, 258, 262, 268, 273, 300, 341, 344, 356, 363, 381, 393, 400, 418, 427, 432, 442, 458, 479, 482, 484, 488, 501, 511, 522, 530, 534, 538, 542, 555, 570, 577, 592, 601, 608, 624, 631], 'Gujarat Lions': [2, 5, 15, 33, 37, 40, 48, 51, 590, 598, 606, 609, 632, 634], 'Kings XI Punjab': [10, 21, 25, 41, 45, 47, 49, 53, 64, 68, 80, 96, 105, 111, 115, 119, 122, 129, 134, 156, 163, 176, 180, 189, 200, 204, 211, 224, 227, 238, 255, 269, 283, 286, 292, 295, 324, 329, 332, 339, 342, 358, 368, 373, 390, 397, 399, 404, 411, 414, 435, 449, 465, 471, 478, 485, 487, 490, 504, 508, 515, 516, 523, 527, 531, 547, 559, 565, 568, 578, 582, 588, 593, 603, 611, 621, 628], 'Kochi Tuskers Kerala': [236, 243, 254, 260, 277, 282, 289], 'Kolkata Knight Riders': [6, 13, 22, 26, 39, 57, 59, 70, 74, 87, 91, 94, 98, 102, 104, 120, 133, 141, 145, 153, 155, 162, 174, 190, 195, 203, 207, 212, 216, 221, 239, 257, 265, 274, 290, 302, 304, 308, 316, 343, 352, 367, 369, 374, 377, 391, 396, 405, 412, 423, 436, 452, 457, 462, 467, 505, 513, 521, 544, 549, 554, 580, 599, 607, 613, 623, 626, 630], 'Mumbai Indians': [1, 23, 43, 46, 52, 58, 62, 71, 81, 101, 108, 112, 117, 131, 137, 142, 149, 152, 161, 169, 175, 182, 187, 198, 206, 214, 218, 220, 225, 229, 230, 246, 256, 259, 266, 272, 276, 281, 298, 318, 326, 335, 350, 359, 362, 385, 389, 394, 407, 416, 420, 422, 429, 433, 446, 456, 461, 469, 472, 483, 489, 496, 500, 507, 514, 517, 525, 529, 533, 540, 548, 551, 566, 572, 575, 576, 584, 587, 596, 618, 622, 629], 'Pune Warriors': [249, 253, 263, 270, 294, 297, 309, 314, 320, 328, 334, 338, 357, 386, 398, 408, 430, 438, 444, 450], 'Rajasthan Royals': [61, 77, 85, 100, 109, 114, 125, 144, 151, 159, 167, 179, 183, 186, 192, 197, 209, 222, 226, 245, 250, 275, 287, 293, 310, 313, 321, 325, 333, 348, 353, 360, 364, 372, 376, 384, 388, 392, 402, 406, 409, 426, 455, 463, 475, 481, 493, 497, 512, 519, 535, 539, 552, 569], 'Rising Pune Supergiant': [3, 12, 16, 27, 28, 32, 42, 55], 'Rising Pune Supergiants': [581, 585, 595, 600, 604, 610, 620], 'Royal Challengers Bangalore': [4, 7, 11, 19, 29, 36, 44, 54, 69, 83, 89, 93, 103, 106, 110, 118, 126, 128, 138, 147, 170, 177, 191, 201, 213, 241, 267, 279, 303, 305, 311, 319, 337, 349, 361, 366, 371, 382, 387, 395, 410, 419, 425, 428, 437, 440, 447, 451, 470, 474, 491, 494, 502, 509, 524, 545, 556, 561, 573, 574, 579, 586, 589, 591, 594, 605, 614, 616, 619, 625], 'Sunrisers Hyderabad': [0, 9, 18, 20, 24, 31, 35, 38, 56, 383, 401, 413, 415, 431, 439, 443, 448, 454, 460, 468, 473, 476, 480, 486, 492, 495, 499, 510, 528, 536, 543, 550, 557, 560, 563, 567, 571, 583, 597, 602, 612, 615, 617, 627, 633, 635]}

In [51]:
df.iloc[5,:]

id                                                         6
season                                                  2017
city                                               Hyderabad
date                                              2017-04-09
team1                                          Gujarat Lions
team2                                    Sunrisers Hyderabad
toss_winner                              Sunrisers Hyderabad
toss_decision                                          field
result                                                normal
dl_applied                                                 0
winner                                   Sunrisers Hyderabad
win_by_runs                                                0
win_by_wickets                                             9
player_of_match                                  Rashid Khan
venue              Rajiv Gandhi International Stadium, Uppal
umpire1                                           A Deshmukh
umpire2                                             NJ Llong
umpire3                                                  NaN
Name: 5, dtype: object

In [59]:
grp.get_group('Gujarat Lions')

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
15,16,2017,Mumbai,2017-04-16,Gujarat Lions,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,N Rana,Wankhede Stadium,A Nand Kishore,S Ravi,NaN
33,34,2017,Rajkot,2017-04-29,Gujarat Lions,Mumbai Indians,Gujarat Lions,bat,tie,0,Mumbai Indians,0,0,KH Pandya,Saurashtra Cricket Association Stadium,AK Chaudhary,CB Gaffaney,NaN
37,38,2017,Pune,2017-05-01,Gujarat Lions,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,5,BA Stokes,Maharashtra Cricket Association Stadium,M Erasmus,C Shamshuddin,NaN
40,41,2017,Delhi,2017-05-04,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,7,RR Pant,Feroz Shah Kotla,M Erasmus,Nitin Menon,NaN
48,49,2017,Kanpur,2017-05-10,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,2,SS Iyer,Green Park,YC Barde,AK Chaudhary,NaN
51,52,2017,Kanpur,2017-05-13,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,8,Mohammed Siraj,Green Park,AK Chaudhary,Nitin Menon,NaN
590,591,2016,Rajkot,2016-04-21,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,10,B Kumar,Saurashtra Cricket Association Stadium,K Bharatan,HDPK Dharmasena,NaN
598,599,2016,Delhi,2016-04-27,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,normal,0,Gujarat Lions,1,0,CH Morris,Feroz Shah Kotla,M Erasmus,S Ravi,NaN
606,607,2016,Rajkot,2016-05-03,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,field,normal,0,Delhi Daredevils,0,8,RR Pant,Saurashtra Cricket Association Stadium,CB Gaffaney,BNJ Oxenford,NaN
609,610,2016,Hyderabad,2016-05-06,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,5,B Kumar,"Rajiv Gandhi International Stadium, Uppal",M Erasmus,S Ravi,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN

In [60]:
df.iloc[634,:]

id                                 635
season                            2016
city                             Delhi
date                        2016-05-27
team1                    Gujarat Lions
team2              Sunrisers Hyderabad
toss_winner        Sunrisers Hyderabad
toss_decision                    field
result                          normal
dl_applied                           0
winner             Sunrisers Hyderabad
win_by_runs                          0
win_by_wickets                       4
player_of_match              DA Warner
venue                 Feroz Shah Kotla
umpire1                      M Erasmus
umpire2                      CK Nandan
umpire3                            NaN
Name: 634, dtype: object

In [61]:
delivery=pd.read_csv('deliveries.csv')

In [124]:
delivery.head(10)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,0,1,0,0,1,1,NaN,NaN,NaN

In [113]:
runs=delivery.groupby('batsman')

In [125]:
sd=runs.get_group('V Kohli')
type(sd)

pandas.core.frame.DataFrame

In [126]:
runs['batsman_runs'].sum().sort_values(ascending=False).head(5)

batsman
SK Raina     4548
V Kohli      4423
RG Sharma    4207
G Gambhir    4132
DA Warner    4014
Name: batsman_runs, dtype: int64

In [127]:
mask=delivery['batsman_runs']==6

In [128]:
new_del=delivery[mask]

In [129]:
new_del.shape[0]

6523

In [130]:
new_del.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(5)

batsman
CH Gayle     266
SK Raina     174
RG Sharma    173
DA Warner    160
V Kohli      160
Name: batsman_runs, dtype: int64

In [131]:
sd=sd.groupby('bowling_team')

In [132]:
sd['batsman_runs'].sum().sort_values(ascending=False).head(5)

bowling_team
Chennai Super Kings    706
Delhi Daredevils       661
Kings XI Punjab        483
Mumbai Indians         447
Sunrisers Hyderabad    439
Name: batsman_runs, dtype: int64

In [ ]:
# isin()
# Find the most destructive death over batsman in the history of IPL
# Strike Rate= (Number of runs/Number of balls)/100e
# Min batsman 200 balls in over 16-20

In [135]:
death_overs=delivery[delivery['over']>15]
death_overs

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
93,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,1,MC Henriques,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
94,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,2,MC Henriques,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,0,0,0,MC Henriques,caught,Sachin Baby
95,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,3,Yuvraj Singh,DJ Hooda,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
96,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,4,DJ Hooda,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
97,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,5,Yuvraj Singh,DJ Hooda,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [157]:
all_batsman=death_overs.groupby('batsman')['batsman_runs'].count()
x=all_batsman>200
batsman_list=all_batsman[x].index.tolist()

In [162]:
final=delivery[delivery['batsman'].isin(batsman_list)]

In [166]:
runs=final.groupby('batsman')['batsman_runs'].sum()

In [168]:
balls=final.groupby('batsman')['batsman_runs'].count()

In [169]:
sr=(runs/balls)*100

In [170]:
sr.sort_values(ascending=False)

batsman
AB de Villiers      145.129059
YK Pathan           140.751445
KA Pollard          140.621266
DA Warner           138.318401
DA Miller           137.709251
JA Morkel           136.938202
Harbhajan Singh     135.194585
SK Raina            134.995548
MS Dhoni            132.835821
KM Jadhav           130.555556
JP Faulkner         129.802956
SPD Smith           128.507127
RG Sharma           128.497251
WP Saha             127.727646
RV Uthappa          127.635135
V Kohli             126.588437
Yuvraj Singh        126.390244
STR Binny           123.747981
AT Rayudu           123.014257
KD Karthik          123.008475
AR Patel            122.672065
DJ Bravo            122.286822
JP Duminy           121.970624
BJ Hodge            121.422376
AD Mathews          120.868114
DJ Hussey           120.072661
LRPL Taylor         120.070838
RA Jadeja           118.792867
DPMD Jayawardene    118.791064
S Dhawan            118.502496
AM Rahane           117.486549
MK Pandey           116.938453
IK Pathan           116.751269
S Badrinath         115.742972
SS Tiwary           114.851485
NV Ojha             114.528024
MK Tiwary           114.127424
Y Venugopal Rao     113.872832
PP Chawla           110.278373
R Vinay Kumar       106.666667
JH Kallis           105.936272
P Kumar             105.263158
A Mishra             89.005236
Name: batsman_runs, dtype: float64

In [173]:

#Merge Function

delivery=pd.read_csv('deliveries.csv')
match=pd.read_csv('matches.csv')

In [176]:
delivery.head(2)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [177]:
match.head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [185]:
new =delivery.merge(match,left_on='match_id',right_on='id')

In [187]:
new.shape

(150460, 39)

In [193]:
season_batsman=new.groupby(['season','batsman'])['batsman_runs'].sum()

In [194]:
season_batsman

season  batsman
2008    A Chopra              42
        A Kumble              13
        A Mishra              37
        A Mukund               0
        A Nehra                3
                            ...
2017    Washington Sundar      9
        YK Pathan            143
        YS Chahal             13
        Yuvraj Singh         252
        Z Khan                 4
Name: batsman_runs, Length: 1531, dtype: int64

In [204]:
season_batsman.sort_values(ascending=False).reset_index().drop_duplicates(subset='season',keep='first').sort_values('season')

    season       batsman  batsman_runs
10    2008      SE Marsh           616
14    2009     ML Hayden           572
9     2010  SR Tendulkar           618
11    2011      CH Gayle           608
2     2012      CH Gayle           733
3     2013    MEK Hussey           733
6     2014    RV Uthappa           660
17    2015     DA Warner           562
0     2016       V Kohli           973
7     2017     DA Warner           641